### ISSUE TITLE
Document appointments table

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#1372]
See https://github.com/opensafely-core/ehrql/issues/1340 for details.

**Comment by sebbacon** [comment]
Some documentation about practice registrations and appointments to crib [here](https://bennettoxford.slack.com/archives/C02HJTL065A/p1689327065988359)

**Comment by iaindillingham** [comment]
Closing, because I think this work has been completed. [The `appointments` table's schema documentation](https://docs.opensafely.org/ehrql/reference/schemas/beta.tpp/#appointments) has:

* a description of the table, which includes information about a corresponding short data report
* descriptions of each column
* types and constraints of each column
* a code snippet that highlights a "gotcha" for cohort-extractor users

I don't know if anyone is using this table, but because of the above, I am confident that this work is "good enough".

**Comment by sebbacon** [comment]
There's one bit of info from the doc I linked that I think _might_ belong here (or at least, a version of it):

> When a patient moves practice, their appointment history is deleted, as this is considered low-value and high-frequency administrative data. Therefore, any research about appointment history should censor patients that change practice. (That said, it’s important to note that appointment data is problematic in general and we advise against studies using it to generate variables).

This (especially the first part) is critical information about appointments. It may be documented adequately obviously elsewhere, but I wanted to make that note.

**Comment by iaindillingham** [comment]
I believe that is covered by #1496, @sebbacon.
