### ISSUE TITLE
Document medications table

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#1376]
See https://github.com/opensafely-core/ehrql/issues/1340 for details.

**Comment by iaindillingham** [comment]
We should document how a researcher would factor a _burn-in period_, _washout period_, or _run-in period_ that covers the time it takes for medications data to stabilize after a patient changes practices.

> **burn-in period**. a fixed period of time after one type of event, during which we exclude other types of event from an analysis.

Doing so is especially important for repeat medications data that relate to allergies, because these must be temporarily shutdown whilst any discrepancies in prescribing between the old practice and the new practice are resolved ([Slack thread][1]).

Burn-in periods are common in epidemiology, and are often specific to the research question ([Slack thread][2]). Here, we should document the specific burn-in period that relates to a patient changing practices.

Thanks, @alschaffer, for your help.

[1]: https://bennettoxford.slack.com/archives/C02HJTL065A/p1689327065988359
[2]: https://bennettoxford.slack.com/archives/C02HJTL065A/p1692270884962919
