### ISSUE TITLE
Document open_prompt table

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#1380]
See https://github.com/opensafely-core/ehrql/issues/1340 for details.

**Comment by iaindillingham** [comment]
Closing, because I think this work has been completed. [The `open_prompt` table's schema documentation](https://docs.opensafely.org/ehrql/reference/schemas/beta.tpp/#open_prompt) has:

* a description of the table, which includes information about a corresponding short data report
* descriptions of each column
* types and constraints of each column

I know that the OpenPROMPT team have looked at the schema documentation, so am confident that this work is "good enough".
