### ISSUE TITLE
Document SUS tables

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#1384]
See https://github.com/opensafely-core/ehrql/issues/1340 for details.

Currently-exposed SUS tables are:

* apcs_cost
* ec_cost
* emergency_care_attendances (but should this be renamed for consistency with other SUS tables?)
* opa_cost
* opa_diag
* opa_proc

**Comment by inglesp** [comment]
https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Live/ might be useful!

**Comment by StevenMaude** [comment]
# Questions

I'm unfamiliar with these tables.

* Not sure about `procedure_code_1` in `opa_proc`. I can't find it anywhere in the database search.
* Not sure about the source of the emergency care admissions. Is this `tbl_Data_SUS_EC`?
* Why are some values duplicated across tables here, rather than joining to the "parent" table? Example: `admission_date` for `apcs` and `apcs_cost`. Are these the same?
* Do the comma-separated data types — example "varchar(3), varchar(5), varchar(50), varchar(8)" — indicate that the data can be any one of these types?

# TODO

Have assumed that the primary key information is the same for each of the tables of a given type as it is in the parent. That is, I've assumed that the `apcs_ident` in `tbl_Data_SEM_APCS` is identical to `apcs_ident` in `tbl_Data_SEM_APCS_2122_Cost`. But could confirm this for definite.

# `apcs`

## From `tbl_Data_SEM_APCS`

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Live/table/1771633/

`apcs_ident`
bigint — APCS identifier
"Primary key - Use this field to join to the other tbl_Data_SEM_APCS_* tables."

`admission_date`
date, datetime — Start date (hospital provider spell) 
"The start date of the hospital provider spell."

`discharge_date`
date, datetime — Discharge date
"The date of discharge from a hospital provider spell."

`spell_core_hrg_sus`
varchar(5) — Healthcare resource group (HRG)
"The core HRG for the spell according to the derivations made by NHS Digital prior to import to the NCDR."

# `apcs_cost`

## From `tbl_Data_SEM_APCS`

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Live/table/1771633/

`apcs_ident`
bigint — APCS identifier
"Primary key - Use this field to join to the other tbl_Data_SEM_APCS_* tables."

`admission_date`
date, datetime — Start date (hospital provider spell)
"The start date of the hospital provider spell."

`discharge_date`
date, datetime — Discharge date
"The date of discharge from a hospital provider spell."

## From `tbl_Data_SEM_APCS_2122_Cost` 

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Live/table/1773646/

`grand_total_payment_mff`
decimal, numeric — Tariff - grand total, including market forces factor (MFF)
"The total payment for the activity (Net_SLA_Payment + Tariff_MFF_Payment)."

`tariff_initial_amount`
int — Tariff - base national tariff 
"The base national tariff."

`tariff_total_payment`
decimal, numeric — Tariff - total payment 
"The total payment according to the national tariff."

# `ec`

## From `tbl_Data_SUS_EC`

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Live/table/1772082/

`ec_ident`
bigint — EC identifier
"Primary key - Use this field to join to the other tbl_Data_SUS_EC_* tables."

`arrival_date`
datetime — Arrival date 
"The date the patient self presented at the accident & emergency department, or arrived in an ambulance at the accident & emergency department."

`sus_hrg_code`
varchar(5) — Healthcare resource group (HRG)
"The core HRG derived by sus+, as a result of HRG grouping, and used for tariff application."

# `ec_cost`

## From `tbl_Data_SUS_EC`

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Live/table/1772082/

`ec_ident`
bigint — EC identifier
"Primary key - Use this field to join to the other tbl_Data_SUS_EC_* tables."

`ec_decision_to_admit_date`
date — Decided to admit date 
"The date a decision to admit was made."

`ec_injury_date`
date — Injury date
"The date the patient was injured."

`arrival_date`
datetime — Arrival date 
"The date the patient self presented at the accident & emergency department, or arrived in an ambulance at the accident & emergency department."

## From `tbl_Data_SUS_EC_2122_Cost`

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Live/table/1773655/

`grand_total_payment_mff`
decimal, numeric — Tariff - grand total, including market forces factor (MFF) 
"The total payment for the activity (Net_SLA_Payment + Tariff_MFF_Payment)."

`tariff_total_payment`
decimal, numeric — Tariff - total payment 
"The total payment according to the national tariff."

# `emergency_care_admissions`

:warning: not sure if I have the correct table; `EC` looks like "emergency care" 

## From `tbl_Data_SUS_EC`

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Live/table/1772082/

:warning: Is what we have down as `id` really from `EC_Ident`?

`id`
bigint — EC identifier
"Primary key - Use this field to join to the other tbl_Data_SUS_EC_* tables."

`arrival_date`
datetime — Arrival date 
"The date the patient self presented at the accident & emergency department, or arrived in an ambulance at the accident & emergency department."

:warning: Is `discharge_destination` from `Discharge_Destination_SNOMED_CT``

`discharge_destination`
varchar(18) — Discharge destination 
"The SNOMED CT concept ID which is used to identify the intended destination of the patient following discharge from the emergency care department."

## From `tbl_Data_SUS_EC_Diagnosis`

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Live/table/1772089/

:warning: Are the `diagnosis_xx` variables from `EC_Diagnosis_XX`?

`diagnosis_01`
`diagnosis_02`
`diagnosis_03`
`diagnosis_04`
`diagnosis_05`
`diagnosis_06`
`diagnosis_07`
`diagnosis_08`
`diagnosis_09`
`diagnosis_10`
`diagnosis_11`
`diagnosis_12`
`diagnosis_13`
`diagnosis_14`
`diagnosis_15`
`diagnosis_16`
`diagnosis_17`
`diagnosis_18`
`diagnosis_19`
`diagnosis_20`
`diagnosis_21`
`diagnosis_22`
`diagnosis_23`
`diagnosis_24`
varchar(18) — Diagnosis (SNOMED CT)
"The SNOMED CT concept ID which is used to identify the patient diagnosis."

# `opa`

## From `tbl_Data_SUS_OPA`

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Faster_SUS/table/1773188/

`opa_ident`
bigint — OPA identifier
"Primary key - Use this field to join to the other tbl_Data_SEM_OPA_* tables."

`appointment_date`
date, datetime — Appointment date
"The date of an appointment."

`attendance_status`
varchar(1) — Attendance status
"Indicates whether or not an appointment for a care contact took place. If the appointment did not take place it also indicates whether or not advanced warning was given."

`consultation_medium_used`
varchar(2) — Consultation medium used
"Identifies the communication mechanism used to relay information between the care professional and the person who is the subject of the consultation, during a care activity."

`first_attendance`
varchar(1) — First attendance
"An indication of whether a patient is making a first attendance or contact; or a follow-up attendance or contact and whether the consultation medium used national code was face to face communication or telephone or telemedicine web camera."

`hrg_code`
varchar(10), varchar(13), varchar(4), varchar(5), varchar(6) — Healthcare resource group (HRG) 
"The HRG produced by the HRG grouper."

`treatment_function_code`
varchar(3), varchar(5), varchar(50), varchar(8) — Treatment function code (TFC)
"The treatment function under which the patient is treated. It may be the same as the main specialty code or a different treatment function which will be the care professional's treatment interest."

# `opa_cost`

## From `tbl_Data_SUS_OPA`

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Faster_SUS/table/1773188/

`opa_ident`
bigint — OPA identifier
"Primary key - Use this field to join to the other tbl_Data_SEM_OPA_* tables."

`appointment_date`
date, datetime — Appointment date
"The date of an appointment."

`referral_request_received_date`
datetime — Referral request received date 
"The date the referral request was received by the health care provider."

## From `tbl_Data_SUS_OPA_2122_Cost`

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Faster_SUS/table/1773671/

`tariff_opp`
decimal — Tariff - OP procedure
"The base national tariff where the procedure tariff is applicable."

`grand_total_payment_mff`
decimal, numeric — Tariff - grand total, including market forces factor (MFF)
"The total payment for the activity (Net_SLA_Payment + Tariff_MFF_Payment)."

`tariff_total_payment`
decimal, numeric — Tariff - total payment
"The total payment according to the national tariff."

# `opa_diag`

## From `tbl_Data_SUS_OPA`

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Faster_SUS/table/1773188/

`opa_ident`
bigint — OPA identifier
"Primary key - Use this field to join to the other tbl_Data_SEM_OPA_* tables."

`appointment_date`
date, datetime — Appointment date
"The date of an appointment."

`referral_request_received_date`
datetime — Referral request received date 
"The date the referral request was received by the health care provider."

## From `tbl_Data_SUS_OPA_Diag`

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Faster_SUS/table/1773050/

`primary_diagnosis_code`
varchar(6), varchar(7) — Diagnosis (ICD)
"The international classification of diseases (ICD) code used to identify the primary diagnosis."

`primary_diagnosis_code_read`
varchar(7) — Diagnosis (read) 
"The read coded clinical terms code to identify the primary diagnosis."

`secondary_diagnosis_code_1`
varchar(6), varchar(7) — Diagnosis (ICD) 
"The international classification of diseases (ICD) code used to identify the secondary patient diagnosis."

`secondary_diagnosis_code_1_read`
varchar(7) — Diagnosis (read) 
"The read coded clinical terms used to identify the secondary patient diagnosis."

# `opa_proc`

## From `tbl_Data_SUS_OPA`

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Faster_SUS/table/1773188/

`opa_ident`
bigint — OPA identifier
"Primary key - Use this field to join to the other tbl_Data_SEM_OPA_* tables."

`appointment_date`
date, datetime — Appointment date
"The date of an appointment."

`referral_request_received_date`
datetime — Referral request received date 
"The date the referral request was received by the health care provider."

## From `tbl_Data_SUS_OPA_Proc`

https://data.england.nhs.uk/ncdr/database/NHSE_SUSPlus_Faster_SUS/table/1773051/

`primary_procedure_code`
varchar(4), varchar(7) — Procedure (OPCS) 
"The OPCS classification of interventions and procedures code which is used to identify the primary patient procedure carried out."

`primary_procedure_code_read`
varchar(7) — Procedure (read) 
"The read coded clinical terms code which is used to identify the primary patient procedure carried out."

`procedure_code_1`
:warning: not sure about this? Not anywhere searching for references in the NHS database. There is a `Procedure_Code_2` which is an OPCS code.

`procedure_code_2_read`
varchar(7) — Procedure (read)
"The read coded clinical terms for a procedure other than the primary procedure (read)."

**Comment by evansd** [comment]
We should document that the various `emergency_care_attendences.diagnosis_XX` fields here:
https://github.com/opensafely-core/ehrql/blob/d2bb7287cf884862a273539a08232e4764929430/ehrql/tables/beta/tpp.py#L284-L307

Only take a limited subset of SNOMED-CT codes, as documented here:
https://www.datadictionary.nhs.uk/data_elements/emergency_care_diagnosis__snomed_ct_.html

This came up because a Cohort Extractor user hit some database issues when trying to match a large codelist against these columns, when in fact this was pointless as most of the codes would never match.

Slack thread here:
https://bennettoxford.slack.com/archives/C028EJH752A/p1697653918759529?thread_ts=1697616032.815989&cid=C028EJH752A
