### ISSUE TITLE
Replace negative IMD values with NULLs

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#1548]
In TPP, -1 is used to indicate a missing IMD value.  We should replace this with NULL in the [table definition in the TPP backend](https://github.com/opensafely-core/ehrql/blob/99cbe958693eb3c7f1c63dae5d52647f450b84e0/ehrql/backends/tpp.py#L158).  As with #1523, we should check the performance impact before making any changes.

There's unlikely to be a problem with backwards compatibility, because if we write a dataset to arrow, we'll try to use an unsigned int for this column (because of [this constraint](https://github.com/opensafely-core/ehrql/blob/99cbe958693eb3c7f1c63dae5d52647f450b84e0/ehrql/tables/beta/tpp.py#L142)) and it'll crash.  But it's possible users are writing to CSV, so we should double check, through GH code search.

**Comment by evansd** [comment]
Thanks for catching this. We should check the performance impact, but I'm less worried about a change like this because (a) the `addresses` table is much smaller than, say, `clinical_events` and (b) we don't tend to filter on `imd_rounded` in any case.

What would have caught this earlier is the thing we've discussed several times, some sort of `validate` command which checks that the constraints we assert in the schema are actually met.

Maybe I should write a placeholder ticket for this so we've got somewhere to link relevant issues to.
