### ISSUE TITLE
Support small number suppression and rounding of measures output

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/ehrql#1666]
Measures generation with cohort extractor supported [optional small number suppression](https://github.com/opensafely-core/cohort-extractor/blob/1c281ea6308998514c569990d632b3cc5c793c5d/cohortextractor/measure.py#L34C1-L39C40).

Support for this in ehrQL will allow more consistent disclosure control. Since the implementation in cohort extractor, we have [updated our disclosure control guidance](https://www.opensafely.org/updated-output-checking-processes/), so this should be done in collaboration with an output checker to make sure the approach is consistent with the updated guidelines.

**Comment by iaindillingham** [comment]
If the sum of suppressed counts is small, then it might be possible to reidentify cases by comparing the sum of unsuppressed counts to the sum of the population. To mitigate this risk, in cohort-extractor, if the sum of suppressed counts is smaller than the threshold, then all of the next smallest counts (i.e. unsuppressed counts) are also suppressed ([code](https://github.com/opensafely-core/cohort-extractor/blob/fcdfdd323a20bb304c375bd039661c0f9b306321/cohortextractor/measure.py#L130-L140)).

cohort-extractor suppresses small counts, but doesn't round. ehrQL will first suppress small counts and will then round (see "[Updated disclosure control guidance](https://www.opensafely.org/updated-output-checking-processes/)"). @LFISHER7, does this mean that ehrQL doesn't need to mitigate this risk?

I don't think it needs to, but would like to check with you.

**Comment by LFISHER7** [comment]
Thanks for looking into this @iaindillingham! Yes, that's correct. We've moved to enforcing rounding (following suppression of small counts) to reduce the risk of secondary disclosure in a way that is consistent, easier to implement and easier to verify - this can replace the previous method rather than being in addition to.

**Comment by LFISHER7** [comment]
Good question! I would like to say no so we can be certain it has been applied when people say it has, but i'm going to check with others to see what they think.

**Comment by iaindillingham** [comment]
I can think of a couple, but I don't know how common they are:

* When a user wants to learn more about measures. They'd generate some dummy tables, calculate some measures, and then compare. (We wouldn't expect this to show up in a commit.)
* When a user wants to use different thresholds/multiples. For example, suppress 10 and round seven. (We would expect this to show up in a commit, ideally with an explanation.)

**Comment by HelenCEBM** [comment]
Agree with Andrea's points that sometimes being able to see or use the unredacted unrounded values is useful. 
- Users may also want to do further calculations with measure values (e.g. group weeks up to longer periods, combine groups, or combine whole measures. If values are redacted and rounded beforehand and there are small values this could lead to large inaccuracies. 
- Overlapping with Andrea's point 2, some research/surveillance projects will naturally be on things affecting small numbers of people so it would be difficult to explore the intermediate results if small numbers have been suppressed already. And users may feel more reassured that their code (as well as codelists) is working correctly if they can see a range of actual values rather than lots of zeros where small numbers may (or may not!) have been suppressed.





helen c
  [19 hours ago](https://bennettoxford.slack.com/archives/C02HJTL065A/p1700493162362399?thread_ts=1700490946.086449&cid=C02HJTL065A)
and similarly i would feel more reassured about my own code if i could see a range of actual values in my results rather than lots of zeros and not being able to tell if it's suppressed or i made a mistake

**Comment by iaindillingham** [comment]
Thanks, @LFISHER7, @alschaffer, and @HelenCEBM. From your comments, we will turn on statistical disclosure control (SDC) by default, but allow a user to turn it off by doing something like this:

```py
measures = create_measures()

measures.configure_sdc(disable=True)

measures.define_measure(...)
```

Turning SDC off in the measure definition file gives us more scope to configure the nature of SDC, should we need to, in the future (e.g. we may want to add alternative SDC strategies).

**Comment by LFISHER7** [comment]
That looks sensible to me!

**Comment by alschaffer** [comment]
Agree. When will this be in effect (as I have code that will be affected)?

**Comment by iaindillingham** [comment]
I'm going to work on it this morning, @alschaffer. You will need to update your code soon after #1746 is merged.

**Comment by iaindillingham** [comment]
I've moved this back to in progress, because although #1746 has been merged, there's some snagging:

- [ ] Update the "[Using the measures framework](https://docs.opensafely.org/ehrql/explanation/measures/)" page
- [ ] Add a conventional commit, so we tag/build a new version
- [ ] Release the new version to the TPP backend
- [ ] Add a platform news item

Which is to say that although #1746 is merged, @alschaffer, you don't need to update your code just yet.

**Comment by iaindillingham** [comment]
I've released this change, @alschaffer. Measures are now subject to disclosure control by default on the TPP backend. Run `opensafely pull` to update your local ehrQL. Platform news and docs updates coming shortly.

**Comment by iaindillingham** [comment]
Okay, all done! _Finally_ closing.
