### ISSUE TITLE
Replace ceiling start_date and end_date in PatientAddress table with null

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/ehrql#1668]
The start_date and end_date fields in the PatientAddress table are non-nullable date fields that can take ceiling values (9999-12-31).  These should be replaced with NULL to avoid unexpected behaviour if a user was to specify start/end > YYYYMMDD.

Performance issues checked in #1523, see comment: https://github.com/opensafely-core/ehrql/issues/1523#issuecomment-1768948693

**Comment by inglesp** [comment]
We should check whether any users are comparing these date fields against 9999-12-31, because if so, the behaviour of the query may have changed.

For instance, `addresses.end_date < "9999-12-31"` would previously have returned a boolean for all addresses, but will now return NULL if the address's end date is NULL.

**Comment by milanwiedemann** [comment]
A quick search on GitHub suggests that there are currently no use cases of date comparisons for: 

- `addresses.start_date` (see [here](https://github.com/search?q=org%3Aopensafely+addresses.start_date&type=code))
- `addresses.end_date` (see [here](https://github.com/search?q=org%3Aopensafely+addresses.end_date&type=code))

The string "9999-12-31" only appears in the context of `practice_registrations`, see search [here](https://github.com/search?q=org%3Aopensafely%20%229999-12-31%22&type=code).

This suggests that there should be no issues replacing "9999-12-31" with NULL for the PatientAddress table.
