### ISSUE TITLE
Update OpenSAFELY docs to refer to ehrQL

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#1676]
Lots of parts of the OpenSAFELY docs refer to cohort-extractor.  We should update these to refer to ehrQL.

@CLStables has put together [this doc](https://docs.google.com/document/d/1qWLvliW6QXspYAOubTr_GeRuNhzjuqmVgqy0n-Q79XY/edit#heading=h.v26uhegfckob) outlining all the places that will need to be updated.

**Comment by milanwiedemann** [comment]
@inglesp are you planning to replace the higher level overview docs about study definitions (https://docs.opensafely.org/study-def/) as part of this? if so I'd wait before updating the co-piloting slides. otherwise I could simply refer to https://docs.opensafely.org/ehrql/tutorial/writing-a-dataset-definition/

**Comment by inglesp** [comment]
> @inglesp are you planning to replace the higher level overview docs about study definitions

Yes!  I'm going to move all of this stuff into a section on cohortextractor.  Currently a WIP, will have something to share next week.
