### ISSUE TITLE
Ignore unrecoverable errors in overnight generative test run

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#1755]
We have recently started to hit `Unexpected EOF from the server` errors from the mssql database in overnight generative test runs.  ([Example](https://github.com/opensafely-core/ehrql/actions/runs/6924003140/job/18832647999).)  These are not interesting, and should not be treated as test failures.

Instead, when running the tests overnight we should catch unrecoverable errors (such as `sqlalchemy.exc.OperationalError`) and exit cleanly.  Since the overnight tests run in batches (to avoid memory leaks in the Trino container) a new batch will be started.

**Comment by Jongmassey** [comment]
AFAICT:
* on occasion the mssql instance spun up during gentesting stops responding and is unrecoverable
* we don't particularly know why this happens
* we don't want the noise of the gentests failing when it does

SO:
* there is an [existing functionality](https://github.com/opensafely-core/ehrql/blob/main/tests/generative/ignored_errors.py) to ignore errors. However, `hypothesis` will keep trying to run tests on a dead/unhappy mssql instance once one of these errors has been encountered
* there doesn't appear to be a convenient way to handle these errors differently to the existing ignored errors in `test_query_model.py`, but there may be a `hypothesis` _escape hatch_ that we could use.
* what could we do with such an escape hatch:
  * end the testing run more gracefully, not wasting time trying to test a dead instance
  * bubble an error all the way up to the bit of bash embedded in `generative-tests.yml` so we can `rm` the container of the dead instance, start a fresh one, and carry on the run

Given that, having discussed this with @inglesp , I think that [just ignoring these errors would be a good first start](https://github.com/opensafely-core/ehrql/pull/1760/files).

@evansd  do you have any thoughts on how this could/should be done differently?

**Comment by evansd** [comment]
My suggestion would be catch this database error and then:
```python
raise KeyboardInterrupt("MSSQL fell over: {e}")
```
Which should terminate the test run immediately and, handily, exit with status code 2 to indicate that it was interrupted rather than that the test failed:
https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.ExitCode

You'd then need to futz around with the embedded bash so that it doesn't exit when the command fails with code 2 and instead just loops back round again.

It's all a bit nasty but it should stop these constant false negatives from the overnight tests while also meaning that it won't silently suppress errors from a broken MSSQL instance if you're running the tests locally.

**Comment by inglesp** [comment]
Oh neat, I hadn't thought about `KeyboardInterupt`.

**Comment by Jongmassey** [comment]
Ooh nifty yeah OK I'll have a crack at that

**Comment by Jongmassey** [comment]
Ah _interesting_ side effect of passing out a `KeyboardInterrupt` and handling this in the bash script such that the loop continues is that you can't Ctrl+C to kill it. This feels unwise.

**Comment by evansd** [comment]
I wondered about that, but you should be able to Ctrl-C twice and get out of it: once to exit the generative test and the next to exit the `just remove-database-containers` command which will run afterwards. I've got into the habit of repeatedly mashing Ctrl-C until things stop so I probably wouldn't even notice anything was different.

Alternatively, with a little bit more work we could get pytest to exit with a custom status code so that we don't confuse it with a real keyboard interrupt.

In `tests/generative/conftest.py` add something like:
```py
class BrokenDatabaseError(KeyboardInterrupt):
    ...


def pytest_keyboard_interrupt(excinfo):
    if isinstance(excinfo.value, BrokenDatabaseError):
        print("[SOME EXPLANATORY TEXT]")
        # First exit code not used by pytest
        sys.exit(6)
```

Then instead of raising `KeyboardInterrupt` you'd raise `BrokenDatabaseError`.

**Comment by Jongmassey** [comment]
A custom status code feels more like how I'd like to approach this
