### ISSUE TITLE
How often do users try to run invalid ehrQL in production?

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#2160]
We are considering adding an ehrQL linter to prevent users from trying to run invalid ehrQL in production.

This is only worth doing if running invalid ehrQL in production is something users actually do, so we should review job-runner's logs to verify this.

**Comment by madwort** [comment]
Ok, so I've been having a grep through the job-runner logs on TPP.

## Total job count

I think I can count ehrql jobs by doing e.g.

```bash
grep -R '"org.opensafely.action": "ehrql"' 2024-*/*/ | wc
```

which gives me 717 jobs in 2023 & 971 jobs in 2024.

## Errors

In order to find some errors to search for, I loaded a codespace with the ehrql tutorial & generated a few errors to see what they look like.

### Traceback

Deliberately creating a typo shows a typical error:

```
$ opensafely exec ehrql:v1 generate-dataset dataset_definition.py 
2024-10-24 10:54:14 [info     ] Compiling dataset definition from dataset_definition.py
Error loading file 'dataset_definition.py':

Traceback (most recent call last):
  File "/workspace/dataset_definition.py", line 11, in <module>
    .lost_for_patient()
     ^^^^^^^^^^^^^^^^
AttributeError: 'medications' object has no attribute 'lost_for_patient'
```

Although this presents as "Failed to import" in the logs rather than "Error loading file". I find 30 examples in 2023 & 5 in 2024, with a variety of types:

* SyntaxError: invalid syntax. Perhaps you forgot a comma?
* SyntaxError: '(' was never closed
* ehrql.codes.CodelistError: No column 'dmd_id' in CSV
* AttributeError: 'ons_deaths' object has no attribute 'sort_by'
* AttributeError: Variable 'configure_dummy_data' has not been defined
* NameError: name 'index_date' is not defined
* ImportError: cannot import name 'wl_clockstops' from 'ehrql.tables.beta.tpp'
* ehrql.file_formats.validation.ValidationError: Missing columns: gp_practice
* TypeError: Invalid variable 'ethnicity'. Dataset variables must be values not whole rows

For example:

* [job](https://jobs.opensafely.org/opioid-prescribing-trends-and-changes-during-covid-19/opioids-covid-research/20880/ygze7m5e4wilon24/) - [missing comma](https://github.com/opensafely/opioids-covid-research/blob/3a6cfdbf29e471d171e1bb27837f462e3fecd05d/analysis/measures_test_4.py#L90)
* [job](https://jobs.opensafely.org/what-was-the-impact-of-covid-19-on-mortality-related-to-venous-thromboembolism-in-england/vte-diagnoses-and-deaths/21299/725lirjusxwqizho/) - [ons deaths does not have sort_by](https://github.com/opensafely/vte-diagnoses-and-deaths/blob/7601661e2bf675a33bc4a2bb17d1cda31401bcf5/analysis/dataset_definition.py#L54)
* [job](https://jobs.opensafely.org/opioid-prescribing-trends-and-changes-during-covid-19/opioids-covid-research/21658/czvg5ohpo3t5vlke/) which is one of [five jobs](https://jobs.opensafely.org/opioid-prescribing-trends-and-changes-during-covid-19/opioids-covid-research/21658/) which I think failed with the same error - which is a [missing close bracket](https://github.com/opensafely/opioids-covid-research/blob/ebb1c38b816554bd39d675f833e6e483056e73f5/analysis/codelists.py#L131-L134)

### population not defined

Removing the dataset definition gives me this error:

```
A population has not been defined; define one with define_population()
```

But I can't find any evidence of this happening to anyone in 2023 or 2024

**Comment by evansd** [comment]
Great work, thanks Tom!

I think some of these might actually be our fault. There have been a few cases where we've released a new feature, published a new ehrQL image, but not actually deployed it on the server. So the user's code runs fine locally and in CI but fails when run for real. Examples which _might_ be this are:

 * `AttributeError: Variable 'configure_dummy_data' has not been defined`
 * `ImportError: cannot import name 'wl_clockstops' from 'ehrql.tables.beta.tpp'`

**Comment by inglesp** [comment]
We've found that ~5% of ehrQL jobs fail in production, and some of these are our fault.

This suggests that it is not worth building a mechanism that prevents users from submitting broken code.
