### ISSUE TITLE
Investigate getting the ehrQL sandbox running in the browser

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#2167]
We have a hypothesis that allowing users to try out ehrQL in the browser will help new users get started with learning ehrQL (because they won't have to install anything or do any setup) and will also be valuable "marketing" for OpenSAFELY.

We should put together a prototype to investigate what it will take to get the sandbox running in the browser.

**Comment by evansd** [comment]
A couple of pointers on this.

Most of the core of ehrQL (including everything needed to validate dataset definitions, run the sandbox, and generate dummy data) is pure Python. There are two places where we compiled dependencies:
 * the database drivers (e.g. `pymssql`, `sqlean`);
 * the file reading/writing code (which at the moment just means `pyarrow`)

The intention of the code is that the query engines (which import the database drivers) are only imported when a given query engine is specified on the command line. So there shouldn't be a hard dependency here.

There _is_ currently a hard dependency on `pyarrow` in the file handling code here:
https://github.com/opensafely-core/ehrql/blob/b422eb9eae63df24e4a7bc3e0aad651ae3fb2262/ehrql/file_formats/__init__.py#L4-L7

But it should be perfectly possible to make that conditional so that `.arrow` file support is only provided if the library is available.

**Comment by bloodearnest** [comment]
How much would the sandbox be affected by lack of arrow support? Would it affect example data?

Wondering if its worth trying to build pyarrow for wasm or not as a solution

**Comment by evansd** [comment]
None, I think. It's used to write `.arrow` files and not for anything else.

**Comment by evansd** [comment]
A simpler alternative to having to mess mainline erhQL to make the import conditional would be to ship the browser version with a `ehrql/file_formats/arrow.py` file which shadows the production one. It could be as simple as:
```py
from ehrql.file_formats.base import FileValidationError

# Making this a subclass of `FileValidationError` means it gets displayed more helpfully to the user
# without a traceback
class UnsupportedFormatError(FileValidationError):
   pass

def raise_error(*args, **kwargs):
    raise UnsupportedFormatError("The `.arrow` format is not available in the browser version of ehrQL")

ArrowRowsReader = raise_error
write_rows_arrow = raise_error
```

**Comment by inglesp** [comment]
We've decided not to prioritise this at the moment.
