### ISSUE TITLE
Add helper functions and reusable variables

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#2201]
In #2164, we have identified several queries that are common to many dataset definitions.  We can now add corresponding helper functions and reusable variables to ehrQL.

For this initiative, we should focus on helper functions and variables that do not require significant _waves hands_ curation work.  For instance, we shouldn't be introducing variables that depend on codelists that might go stale, and even an ethnicity variable is probably out of scope.

I suggest doing this in three parts:

* identify the helper functions and variables that we want to offer
* come up with a good API for each function and variable
* write the code

Somebody who knows ehrQL well should be involved in the second step's design work, but the implementation in the third step would be suitable for somebody new to the codebase.

**Comment by rw251** [comment]
The following are tickets for things to implement:

- [ ] - #2206 
- [ ] - #2207 
- [ ] - #2208 
- [ ] - #2010 
- [x] - #1363  

Most other things require maintenance of clinical code sets, or being opinionated about the approach, and would most likely fall under a variables library, rather than something baked into ehrql. These are things we should do over time, but not in this initiative.

**Comment by inglesp** [comment]
Closing.  We can revisit #2208 in future.
