### ISSUE TITLE
Consider explaining core and non-core tables

### ISSUE THREAD

**Issue by alarthast** [opensafely-core/ehrql#2285]
In the old tutorial we had this tip:
https://github.com/opensafely-core/ehrql/blob/8896d4fcb3a317c6d2f3cb64f40b28a863850f4c/docs/tutorial/writing-a-dataset-definition/index.md?plain=1#L24-L29

We don't really say this in the new tutorial, so the user would have to wait until they get to the explanations to find out. This might not be a big deal.

https://github.com/opensafely-core/ehrql/blob/8896d4fcb3a317c6d2f3cb64f40b28a863850f4c/docs/explanation/backend-tables.md?plain=1#L10-L13

https://github.com/opensafely-core/ehrql/blob/8896d4fcb3a317c6d2f3cb64f40b28a863850f4c/docs/explanation/backend-tables.md?plain=1#L15-L18

https://github.com/opensafely-core/ehrql/blob/8896d4fcb3a317c6d2f3cb64f40b28a863850f4c/docs/explanation/backend-tables.md?plain=1#L36-L40

**Comment by inglesp** [comment]
I think I want the tutorial to focus on ehrQL the language, so that it could in principle be used for learning ehrQL for eg OpenSAFELY schools.  As such, we want to avoid muddying the water with discussion about where the tables come from.  We may have to revisit this if it proves to be a source of confusion.
