### ISSUE TITLE
New efficient measures implementation

### ISSUE THREAD

**Issue by benbc** [opensafely-core/ehrql#42]

**Comment by evansd** [comment]
Adding a note here because I'm assuming this issue will be looked at by whoever designs the new measures API.

It would be good to enforce that numerator and denominator definitions are such that a patient can only be a member of the numerator if they are also a member of the denominator.

See Slack threads here for where our inability to enforce this in cohortextractor has lead to confusion:
https://bennettoxford.slack.com/archives/C03FB777L1M/p1665483592932119
https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1664978145256269

**Comment by evansd** [comment]
Closing as we have now (for better or worse) implemented _a_ measures API that we need to live with.

Making the implementation of that API efficient is a separate issue, tracked as:
 * #2294
