### ISSUE TITLE
Bump Docker image to v1

### ISSUE THREAD

**Issue by benbc** [opensafely-core/ehrql#934]
Requires a change to the Docker image build and also to the OpenSAFELY CLI where we currently hard-code the Data Builder image version.

**Comment by StevenMaude** [comment]
What change is needed to the Docker image build here? The image version is pulled from the repository tag. So when the tag version gets updated to v1, then the image should do too. Perhaps I've missed something though.

To update the major version of the tag to `v1`, we'd have to manually push a `v1.0.0` tag and build by manually running the "Build and publish image" workflow, or [use a commit with a message of the form](https://github.com/mathieudutour/github-tag-action#bumping):

> ```
> Commit summary goes here
>
> BREAKING CHANGE: Release ehrQL v1  
> ```

to trigger the tag action we use into incrementing the version.

Semantically the "`BREAKING CHANGE`" is a little bit idiosyncratic: it's not really a breaking change in this `v0` to `v1` case, but simply a version number increment. But one advantage here is that everything *should* be automatically done for us, instead of a manual process.

***

I think the required change in the OpenSAFELY CLI is [this version number](https://github.com/opensafely-core/opensafely-cli/blob/9a2f28eaf3ee04a08f4a2088f261d32275d76bc9/opensafely/pull.py#L131-L133) and the [associated test](https://github.com/opensafely-core/opensafely-cli/blob/9a2f28eaf3ee04a08f4a2088f261d32275d76bc9/tests/test_pull.py).

**Comment by StevenMaude** [comment]
I opened opensafely-core/opensafely-cli#231 as a draft to have the changes ready there.

**Comment by inglesp** [comment]
Note we'll also want to remove `hosptalisations.primary_diagnoses` (see #1248).

**Comment by evansd** [comment]
There are a few other bits and pieces. I'll make a checklist (feel free to edit this comment to expand or to add links to issues as we create them):

 * [ ] Remove `hosptalisations.primary_diagnoses`:
   #1248
 * [ ] Remove the `databuilder` import shims
 * [ ] Stop publishing the `databuilder` docker image
 * [ ] Move `ehrql.tables.beta` to `ehrql.tables`
 * [ ] Remove the deprecated `configure_dummy_dataset` alias:
       https://github.com/opensafely-core/ehrql/blob/4fdb6452aa1333310e1f0530ff66ee5788426706/ehrql/query_language.py#L79-L84
 * [ ] Should we make the default dummy population size much smaller so it runs faster and displays a tractable number of results in the console by default?
